# Generated by Django 4.2.5 on 2023-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
